function grille = gridDisplay(X_t, Y_t, Grid, muscle, option)
    G = Grid;   % example 5x5 grid
    f = figure;
    
    X_t_one = unique(X_t);
    Y_t_one = unique(Y_t);
    
    t = uitable(f, ...
        'Data', G, ...
        'ColumnName', cellstr("X " + X_t_one), ...
        'RowName', cellstr("Y " + Y_t_one), ...
        'Units', 'normalized', ...
        'Position', [0 0 1 0.9]);   % fill the whole figure
    t.FontSize = 15;
    
    if nargin < 5 || isempty(option)
        title=['Mean MEP values (uV) for the ' muscle];
    else
        sessionNb = option;
        str_sessionNb = num2str(sessionNb);
        title=['MEP values (uV) for the ' muscle ' for the session ' str_sessionNb];
    end

    uicontrol(f, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[0 0.92 1 0.07], ...
        'String',title, ...
        'FontSize',15, ...
        'FontWeight','bold', ...
        'HorizontalAlignment','center');
end